import type { NextPage } from 'next';
import Head from 'next/head';
import Organisms from '../components/organisms';

const styles = {
  backgroundColor: '#000',
};

const Home: NextPage = () => {
  return (
    <div style={styles}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <body style={styles}></body>
      <Organisms />
    </div>
  );
};

export default Home;
